{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import MySQLdb\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "db = MySQLdb.connect(\"localhost\",\"root\",\"123456\")\n",
    "db.set_character_set(\"gbk\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 各交易所一分鐘資料"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "DL = {'AY':'A_1','AM':'A_1','AX':'A_1','CS':'CS','FB':'FB','I':'I','JD':'JD','JM':'JM','L':'L',\\\n",
    "      'BB':'BB','M':'M','PP':'PP','V':'V','Y':'Y','BM':'A_2','CM':'C','PM':'P','JMI':'J'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ami' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ax13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ay01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ay03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ay05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ay07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ay09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ay11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bb13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bbmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'bmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cs03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cs05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cs07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cs09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cs11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'cs13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'csmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fb13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'fbmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'i13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'imi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm06' already exists\")\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jm13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jmmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jd13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'jdmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'l13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'lmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'm13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'mmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'pp13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ppmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v12' already exists\")\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'v13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'vmi' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'y13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'ymi' already exists\")\n"
     ]
    }
   ],
   "source": [
    "future_type_list = [\"AM\",\"AX\",\"AY\",\"BB\",\"BM\",\"CM\",\"CS\",\"FB\",\"I\",\"JM\",\"JD\",\"L\",\"M\",\"PM\",\"PP\",\"V\",\"Y\"]\n",
    "DATA_DIR = \"../1分钟 商品期货/商品期货1分钟2014/DL\"\n",
    "for future_type in future_type_list:\n",
    "    for filename in os.listdir(DATA_DIR): \n",
    "        cursor = db.cursor()\n",
    "        dbname = DL[future_type]\n",
    "        \n",
    "        #sql = \"CREATE DATABASE IF NOT EXISTS \" + dbname\n",
    "        #cursor.execute(sql)\n",
    "        \n",
    "        get_name = filename.split(\".csv\")[0]\n",
    "        get_contract_name = get_name.split(\"DL\")[1]\n",
    "        \n",
    "        try:\n",
    "            if(get_contract_name.find(future_type) == 0):\n",
    "                sql = \"CREATE TABLE IF NOT EXISTS \" + dbname +\".\"+ get_contract_name + \\\n",
    "                      \" (Date DATE,\\\n",
    "                        Time TIME(5),\\\n",
    "                        Open FLOAT,\\\n",
    "                        High FLOAT,\\\n",
    "                        Low FLOAT,\\\n",
    "                        Clos FLOAT,\\\n",
    "                        Volume FLOAT,\\\n",
    "                        OI FLOAT)\"\n",
    "                cursor.execute(sql)\n",
    "                \n",
    "                data = pd.read_csv(DATA_DIR+\"/\"+filename,header=None,engine='python')\n",
    "            \n",
    "                for i in range(len(data)):\n",
    "                    sql = \"INSERT INTO \" + dbname + \".\" + get_contract_name + \" VALUES (%s,%s,%s,%s,%s,%s,%s,%s)\"\n",
    "                    cursor.execute(sql.format(),(data.iloc[i][0],data.iloc[i][1],data.iloc[i][2],data.iloc[i][3],data.iloc[i][4],\n",
    "                                   data.iloc[i][5],data.iloc[i][6],data.iloc[i][7]))\n",
    "           \n",
    "        except BaseException as e:          \n",
    "            continue\n",
    "        cursor.close()\n",
    "    db.commit()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 大商所代碼分不出來的"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "DL_O = {'B':'A_2','C':'C','J':'J','P':'P'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'b13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'c13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'j13' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p01' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p02' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p03' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p04' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p05' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p06' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p07' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p08' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p09' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p10' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p11' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p12' already exists\")\n",
      "C:\\Users\\Philip\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:17: Warning: (1050, \"Table 'p13' already exists\")\n"
     ]
    }
   ],
   "source": [
    "future_type_list = [\"B\",\"C\",\"J\",\"P\"]\n",
    "DATA_DIR = \"../1分钟 商品期货/商品期货1分钟2014/DL_O\"\n",
    "for future_type in future_type_list:\n",
    "    for filename in os.listdir(DATA_DIR): \n",
    "        cursor = db.cursor()\n",
    "        dbname = DL_O[future_type]\n",
    "        \n",
    "        #sql = \"CREATE DATABASE IF NOT EXISTS \" + dbname\n",
    "        #cursor.execute(sql)\n",
    "        \n",
    "        get_name = filename.split(\".csv\")[0]\n",
    "        get_contract_name = get_name.split(\"DL\")[1]\n",
    "        \n",
    "        try:\n",
    "            if(get_contract_name.find(future_type) == 0):\n",
    "                sql = \"CREATE TABLE IF NOT EXISTS \" + dbname +\".\"+ get_contract_name + \\\n",
    "                      \" (Date DATE,\\\n",
    "                        Time TIME(5),\\\n",
    "                        Open FLOAT,\\\n",
    "                        High FLOAT,\\\n",
    "                        Low FLOAT,\\\n",
    "                        Clos FLOAT,\\\n",
    "                        Volume FLOAT,\\\n",
    "                        OI FLOAT)\"\n",
    "                cursor.execute(sql)\n",
    "                \n",
    "                data = pd.read_csv(DATA_DIR+\"/\"+filename,header=None,engine='python')\n",
    "            \n",
    "                for i in range(len(data)):\n",
    "                    sql = \"INSERT INTO \" + dbname + \".\" + get_contract_name + \" VALUES (%s,%s,%s,%s,%s,%s,%s,%s)\"\n",
    "                    cursor.execute(sql.format(),(data.iloc[i][0],data.iloc[i][1],data.iloc[i][2],data.iloc[i][3],data.iloc[i][4],\n",
    "                                   data.iloc[i][5],data.iloc[i][6],data.iloc[i][7]))\n",
    "           \n",
    "        except BaseException as e:         \n",
    "            continue\n",
    "        cursor.close()\n",
    "    db.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
